
package MainPackage;

import java.awt.Color;

/**
 *
 * @author Abdul Sami
 */
public class TableForgroundColor extends POS
{
    public static void ChangeTableColor()
    {
        if(a1.size()>0)
            {
                Table1.setForeground(Color.RED);
            }else
            {
                Table1.setForeground(Color.BLACK);
            }
        //****************************************
        if(a2.size()>0)
            {
                Table2.setForeground(Color.RED);
            }else
            {
                Table2.setForeground(Color.BLACK);
            }
        //****************************************
        if(a3.size()>0)
            {
                Table3.setForeground(Color.RED);
            }else
            {
                Table3.setForeground(Color.BLACK);
            }
        //****************************************
        if(a4.size()>0)
            {
                Table4.setForeground(Color.RED);
            }else
            {
                Table4.setForeground(Color.BLACK);
            }
        //****************************************
        if(a5.size()>0)
            {
                Table5.setForeground(Color.RED);
            }else
            {
                Table5.setForeground(Color.BLACK);
            }
        //****************************************
        if(a6.size()>0)
            {
                Table6.setForeground(Color.RED);
            }else
            {
                Table6.setForeground(Color.BLACK);
            }
        //****************************************
        if(a7.size()>0)
            {
                Table7.setForeground(Color.RED);
            }else
            {
                Table7.setForeground(Color.BLACK);
            }
        //****************************************
        if(a8.size()>0)
            {
                Table8.setForeground(Color.RED);
            }else
            {
                Table8.setForeground(Color.BLACK);
            }
        //****************************************
        if(a9.size()>0)
            {
                Table9.setForeground(Color.RED);
            }else
            {
                Table9.setForeground(Color.BLACK);
            }
        //****************************************
        if(a10.size()>0)
            {
                Table10.setForeground(Color.RED);
            }else
            {
                Table10.setForeground(Color.BLACK);
            }
        //****************************************
        if(a11.size()>0)
            {
                Table11.setForeground(Color.RED);
            }else
            {
                Table11.setForeground(Color.BLACK);
            }
        //****************************************
        if(a12.size()>0)
            {
                Table12.setForeground(Color.RED);
            }else
            {
                Table12.setForeground(Color.BLACK);
            }
        //****************************************
        if(a13.size()>0)
            {
                Table13.setForeground(Color.RED);
            }else
            {
                Table13.setForeground(Color.BLACK);
            }
        //****************************************
        if(a14.size()>0)
            {
                Table14.setForeground(Color.RED);
            }else
            {
                Table14.setForeground(Color.BLACK);
            }
        //****************************************
        if(a15.size()>0)
            {
                Table15.setForeground(Color.RED);
            }else
            {
                Table15.setForeground(Color.BLACK);
            }
        //****************************************
        if(a16.size()>0)
            {
                Table16.setForeground(Color.RED);
            }else
            {
                Table16.setForeground(Color.BLACK);
            }
        //****************************************
        if(a17.size()>0)
            {
                Table17.setForeground(Color.RED);
            }else
            {
                Table17.setForeground(Color.BLACK);
            }
        //****************************************
        if(a18.size()>0)
            {
                Table18.setForeground(Color.RED);
            }else
            {
                Table18.setForeground(Color.BLACK);
            }
        //****************************************
        if(a19.size()>0)
            {
                Table19.setForeground(Color.RED);
            }else
            {
                Table19.setForeground(Color.BLACK);
            }
        //****************************************
        if(a20.size()>0)
            {
                Table20.setForeground(Color.RED);
            }else
            {
                Table20.setForeground(Color.BLACK);
            }
        //****************************************
        
        
    }
    
}
